# Generated by Django 4.0.2 on 2022-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_estimation', '0003_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ud', models.FloatField(max_length=10)),
                ('nd', models.FloatField(max_length=10)),
                ('phyh', models.FloatField(max_length=10)),
                ('phyl', models.FloatField(max_length=10)),
            ],
        ),
    ]
