# Generated by Django 4.0.2 on 2022-03-07 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('power_estimation', '0004_ctrl'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrl',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
